#!/bin/sh

# Copyright (C) 2020 UBports Foundation
#
# jumpercable is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# jumpercable is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with jumpercable.  If not, see <http://www.gnu.org/licenses/>.

# shellcheck source=usr/lib/lxc-android-config/common.sh

/bin/mount -t devtmpfs devtmpfs /dev
/bin/mount -t sysfs sysfs /sys

mount_Z01R() {
	mount -t ext4 -o discard,data=journal /dev/sda16 /userdata
}

initial_porting_script() {
	echo "$(date) custom_jumpercable loaded" >> /userdata/initial_boot.log
	echo "-- lxc-checkconfig --" >> /userdata/initial_boot.log
	lxc-checkconfig >> /userdata/initial_boot.log
	echo >> /userdata/initial_boot.log
	echo "-- mount --" >> /userdata/initial_boot.log
	mount >> /userdata/initial_boot.log
	sync
}

dmesg_dump() {
	mv /pre_systemd_dmesg.log /pre_systemd_dmesg_last.log
	bash -c 'dmesg -w > /pre_systemd_dmesg.log' &
}

protected_mount() {
	part_name="$1"
	part_blk="$2"
	mount_point="$3"

	new_mount_point=/userdata/protected_rw_parts/$1

	if ! [ -e "$new_mount_point" ]
	then
		mkdir -p "${new_mount_point}_ref"
		mount "$part_blk" "${new_mount_point}_ref"
		cp -a "${new_mount_point}_ref" "$new_mount_point"
		umount "${new_mount_point}_ref"
	fi

	mount -o bind "$new_mount_point" "$mount_point"
}

add_android_root_dirs() {
	mount -o remount,rw /

	# this actually fails, /var/lib/lxc/android/android-rootfs.img is perfectly sized
	mount /var/lib/lxc/android/android-rootfs.img /android
	if ! [ -e /android/APD ]
	then
		umount /android
		dd if=/dev/zero bs=10M count=1 >> /var/lib/lxc/android/android-rootfs.img
		e2fsck -f /var/lib/lxc/android/android-rootfs.img
		resize2fs /var/lib/lxc/android/android-rootfs.img
		mount /var/lib/lxc/android/android-rootfs.img /android
		mkdir -p /android/APD
		mkdir -p /android/asdf
	fi
	umount /android
	#mount -o remount,ro /
}

mount_android() {
	# mount images
	mount -o ro /var/lib/lxc/android/android-rootfs.img /android
	mount -o ro /vendor.img /android/vendor

	# /android/data
	mkdir -p /userdata/android_data
	mount -o bind /userdata/android_data /android/data

	# /android/mnt
	mount -t tmpfs tmpfs /android/mnt

	# mount configfs
	mount -t configfs configfs /android/config
}

bind_overlay() {
	for f in $(find /overlay_bind)
	do
		if [ -f "$f" ]
		then
			tgt="$(echo $f | sed -e 's#/overlay_bind##')"
			echo binding "$f" to "$tgt"
			mount -o bind "$f" "$tgt"
		fi
	done
}

charger_mode() {
	# TODO
	echo "TODO: charger mode"
}

prep_hardware() {
	# wifi
	echo "ON" > /dev/wlan &

	# torch
	chown 32011:32011 '/sys/class/leds/led:torch_0/brightness' '/sys/class/leds/led:switch_0/brightness'

	# disable gesture reports, droidian mobile-settings likes to enable it, but in a way that the report doesn't get send on evdev, then eventually triggers a oops
	while ! [ -e /sys/bus/i2c/devices/3-0038/fts_gesture_mode ]
	do
		sleep 1
	done
	echo 0 > /sys/bus/i2c/devices/3-0038/fts_gesture_mode
	mount -o bind /dev/null /sys/bus/i2c/devices/3-0038/fts_gesture_mode


	# set cpu governor
	for f in /sys/devices/system/cpu/cpufreq/policy*/scaling_governor; do echo 'schedutil' | tee $f; done
}

nm_resolv() {
	rm /etc/resolv.conf
	ln -s /var/run/NetworkManager/resolv.conf /etc/resolv.conf
}

# Make sure to set up everything only on first-stage boot.
if [ ! -e /proc/self/exe ]; then
	export PATH=/bin:/usr/bin:/sbin:/usr/sbin

	mount -o remount,rw /

	# Put all of this script's output into log file
	exec 1>/custom_jumpercable.log 2>&1

	echo "<< Ubuntu Touch first stage init >>"

	# Mount a tmpfs in /run of rootfs to put the future image.fstab
	mount -o rw,nosuid,noexec,relatime,mode=755 -t tmpfs tmpfs /run
	#mount -t devtmpfs devtmpfs /dev
	mkdir /dev/pts
	mount -t devpts -o noexec,nosuid,gid=5,mode=0620 devpts /dev/pts || true
	mount -t sysfs none /sys
	mount -t proc none /proc

	# Distinguish between halium-boot & jumpercable boot process
	touch /dev/.halium_jumpercable
	chmod 000 /dev/.halium_jumpercable

	add_android_root_dirs
	mount_android
	bind_overlay
	charger_mode
	prep_hardware
	nm_resolv
	initial_porting_script
	#process_bind_mounts
	dmesg_dump
fi

# Execute actual init now
exec /sbin/init $@
